In [358]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error as mse
from sklearn.ensemble import *
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.decomposition import PCA
from scipy.stats import mode

In [322]:
airbnb = pd.read_csv("train.csv")
airbnb.head()

c:\users\zhaow\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3169: DtypeWarning: Columns (30) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,id,name,summary,space,description,experiences_offered,neighborhood_overview,notes,transit,access,...,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,is_business_travel_ready,cancellation_policy,require_guest_profile_picture,require_guest_phone_verification,calculated_host_listings_count,reviews_per_month
0,22267382,Modern and Cozy Large Studio in Brooklyn,Modern large studio with new amenities and app...,Our place is a little quiet sanctuary in the h...,Modern large studio with new amenities and app...,none,"BAM, Barclays, Brooklyn City Point, Fort Green...",NaN,"Subway: 2,3,4,5,A,C,B,Q,G",Washer/Dryer Dishwasher Internet Gym Roof Top ...,...,10.0,10.0,10.0,t,f,flexible,f,f,1,0.59
1,2473861,Royal Harlem TRIPLEX Home 5 Beds,Harlem is back and so gorgeous! Visit and expl...,Harlem is back and so gorgeous! Visit and expl...,Harlem is back and so gorgeous! Visit and expl...,none,HARLEM is a piece of real NY history overflowi...,HARLEM RESTAURANTS Red Rooster Harlem -- excel...,PUBLIC TRANSPORTATION: Conveniently near all p...,The WHOLE ENTIRE HOUSE,...,9.0,9.0,9.0,t,f,moderate,f,f,3,2.47
2,25079703,Sunny East Village Studio,"Clean, hip and well designed sun drenched East...",This is a rare East Village studio with it's h...,"Clean, hip and well designed sun drenched East...",none,East Village is one of the last remaining neig...,NaN,NaN,You'll have access to the entire space - it's ...,...,10.0,10.0,10.0,f,f,moderate,f,f,1,0.89
3,9342478,"Beautiful, airy, light-filled room","Private, spacious, comfortable room in 2-bed f...","Big closet, two big windows, tall ceiling and ...","Private, spacious, comfortable room in 2-bed f...",none,One block from Morgan L stop. Super cool area....,NaN,NaN,NaN,...,NaN,NaN,NaN,f,f,flexible,f,f,1,NaN
4,4866426,Private Room in Prime Brooklyn Spot,"Comfy, quiet and big private room in a three b...",This big old apartment that we love and take c...,"Comfy, quiet and big private room in a three b...",none,I absolutely love this neighborhood - right at...,Just a note about the space: The window in you...,Super convenient to almost all subway lines. A...,Your room has a very comfortable queen sized b...,...,10.0,10.0,10.0,f,f,flexible,f,f,1,3.14

In [323]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33538 entries, 0 to 33537
Data columns (total 65 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   id                                33538 non-null  int64
 1   name                              33526 non-null  object
 2   summary                           32266 non-null  object
 3   space                             23038 non-null  object
 4   description                       33230 non-null  object
 5   experiences_offered               33538 non-null  object
 6   neighborhood_overview             19948 non-null  object
 7   notes                             13447 non-null  object
 8   transit                           20796 non-null  object
 9   access                            19304 non-null  object
 10  interaction                       18670 non-null  object
 11  house_rules                       19983 non-null  object
 12  host_id                           33538 non-null  int64
 13  host_name                         33533 non-null  object
 14  host_since                        33533 non-null  object
 15  host_location                     33424 non-null  object
 16  host_about                        20374 non-null  object
 17  host_response_time                17345 non-null  object
 18  host_response_rate                17345 non-null  object
 19  host_acceptance_rate              0 non-null      float64
 20  host_is_superhost                 33533 non-null  object
 21  host_neighbourhood                28832 non-null  object
 22  host_listings_count               33533 non-null  float64
 23  host_verifications                33538 non-null  object
 24  host_has_profile_pic              33533 non-null  object
 25  host_identity_verified            33533 non-null  object
 26  neighbourhood_cleansed            33538 non-null  object
 27  neighbourhood_group_cleansed      33538 non-null  object
 28  city                              33499 non-null  object
 29  state                             33528 non-null  object
 30  zipcode                           33053 non-null  object
 31  market                            33448 non-null  object
 32  country_code                      33538 non-null  object
 33  country                           33538 non-null  object
 34  property_type                     33538 non-null  object
 35  room_type                         33538 non-null  object
 36  accommodates                      33538 non-null  int64
 37  bathrooms                         33478 non-null  float64
 38  bedrooms                          33505 non-null  float64
 39  beds                              33507 non-null  float64
 40  bed_type                          33538 non-null  object
 41  amenities                         33538 non-null  object
 42  square_feet                       341 non-null    float64
 43  price                             33538 non-null  float64
 44  guests_included                   33538 non-null  int64
 45  extra_people                      33538 non-null  object
 46  minimum_nights                    33538 non-null  int64
 47  maximum_nights                    33538 non-null  int64
 48  number_of_reviews                 33538 non-null  int64
 49  first_review                      26591 non-null  object
 50  last_review                       26593 non-null  object
 51  review_scores_rating              25874 non-null  float64
 52  review_scores_accuracy            25844 non-null  float64
 53  review_scores_cleanliness         25859 non-null  float64
 54  review_scores_checkin             25829 non-null  float64
 55  review_scores_communication       25849 non-null  float64
 56  review_scores_location            25830 non-null  float64
 57  review_scores_value               25827 non-null  float64
 58  instant_bookable                  33538 non-null  object
 59  is_business_travel_ready          33538 non-null  object
 60  cancellation_policy               33538 non-null  object
 61  require_guest_profile_picture     33538 non-null  object
 62  require_guest_phone_verification  33538 non-null  object
 63  calculated_host_listings_count    33538 non-null  int64
 64  reviews_per_month                 26591 non-null  float64
dtypes: float64(15), int64(8), object(42)
memory usage: 16.6+ MB

In [324]:
airbnb.describe()

,id,host_id,host_acceptance_rate,host_listings_count,accommodates,bathrooms,bedrooms,beds,square_feet,price,...,number_of_reviews,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,reviews_per_month
count,3.353800e+04,3.353800e+04,0.0,33533.000000,33538.000000,33478.000000,33505.000000,33507.000000,341.000000,33538.000000,...,33538.000000,25874.000000,25844.000000,25859.000000,25829.000000,25849.000000,25830.000000,25827.000000,33538.000000,26591.000000
mean,1.566316e+07,5.420691e+07,NaN,10.006799,2.856789,1.141376,1.176869,1.571313,738.958944,145.177291,...,21.635548,93.751488,9.599443,9.255153,9.737466,9.754304,9.500542,9.374647,3.956288,1.429904
std,8.788870e+06,6.149736e+07,NaN,85.869452,1.848491,0.425003,0.744365,1.054226,580.780447,133.085709,...,40.488277,8.315867,0.819684,1.073818,0.706306,0.688775,0.781516,0.888392,12.687366,1.672336
min,2.515000e+03,2.830000e+02,NaN,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,20.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,1.000000,0.010000
25%,8.173466e+06,7.130984e+06,NaN,1.000000,2.000000,1.000000,1.000000,1.000000,400.000000,69.000000,...,1.000000,91.000000,9.000000,9.000000,10.000000,10.000000,9.000000,9.000000,1.000000,0.210000
50%,1.633786e+07,2.662292e+07,NaN,1.000000,2.000000,1.000000,1.000000,1.000000,700.000000,109.000000,...,5.000000,96.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,0.770000
75%,2.276632e+07,8.248502e+07,NaN,2.000000,4.000000,1.000000,1.000000,2.000000,1000.000000,175.000000,...,23.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,2.000000,2.140000
max,2.977318e+07,2.240015e+08,NaN,2271.000000,16.000000,16.500000,10.000000,18.000000,5000.000000,1999.000000,...,557.000000,100.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,132.000000,19.890000

In [325]:
# 初步drop缺失值过多、长段文字、或者host-unique的features
def drop_initial(df): 
    cols = ["id", "name", "summary", "space", "experiences_offered", 
            "access", "host_acceptance_rate", "notes",
            "description", "neighborhood_overview", "interaction",
            "house_rules", "host_id", "host_name", "host_about",
            "host_location", "city", "state", "zipcode", "country",
            "country_code", "host_response_time", "host_neighbourhood",
            "host_has_profile_pic", "host_listings_count", "market",
            "host_response_rate", "square_feet", "host_verifications",
            "maximum_nights", "calculated_host_listings_count",
            "require_guest_profile_picture", "minimum_nights",
            "is_business_travel_ready", "first_review", "last_review",
            "transit"
           ]
    return df.drop(cols,  axis = 1)

In [326]:
def to_num(df):
    df["extra_people"] = df.extra_people.str.replace("$", "", regex = False).astype(float)
    return df
airbnb = to_num(airbnb)

In [327]:
def remove_outliers(data):
    df = data.copy(deep = True)
    df = df[(df["reviews_per_month"] < 10) | (df["reviews_per_month"].isnull())]
    df = df[(df["bathrooms"] < 10) | (df["bathrooms"].isnull())]
    df = df[(df["review_scores_cleanliness"] > 2) | (df["review_scores_cleanliness"].isnull())]
    df = df[(df["review_scores_accuracy"] > 2) | (df["review_scores_accuracy"].isnull())]
    df = df[(df["review_scores_location"] > 2) | (df["review_scores_location"].isnull())]
    df = df[(df["review_scores_checkin"] > 2) | (df["review_scores_checkin"].isnull())]
    df = df[(df["review_scores_communication"] > 2) | (df["review_scores_communication"].isnull())]
    df = df[(df["review_scores_value"] > 2) | (df["review_scores_value"].isnull())]
    df = df[(df["number_of_reviews"] < 300) | (df["number_of_reviews"].isnull())]
    return df

In [328]:
cur = remove_outliers(drop_initial(airbnb))

In [335]:
for col in cur.columns:
    if isinstance(cur[col][0], str) :
        print("----------%s----------"%col)
        print(cur[col].value_counts(dropna=False))

----------host_since----------
2015-03-30    98
2016-03-03    92
2014-10-14    85
2015-12-16    83
2014-05-28    71
              ..
2010-01-28     1
2011-02-07     1
2010-06-23     1
2009-12-30     1
2009-07-18     1
Name: host_since, Length: 3284, dtype: int64
----------host_is_superhost----------
f      27805
t       5473
NaN        5
Name: host_is_superhost, dtype: int64
----------host_identity_verified----------
t      16734
f      16544
NaN        5
Name: host_identity_verified, dtype: int64
----------neighbourhood_cleansed----------
Williamsburg                  2741
Bedford-Stuyvesant            2377
Harlem                        1880
Bushwick                      1660
Upper West Side               1442
                              ...
Little Neck                      1
New Dorp                         1
Eltingville                      1
Bay Terrace, Staten Island       1
Rossville                        1
Name: neighbourhood_cleansed, Length: 220, dtype: int64
----------neighbourhood_group_cleansed----------
Manhattan        15340
Brooklyn         13467
Queens            3612
Bronx              650
Staten Island      214
Name: neighbourhood_group_cleansed, dtype: int64
----------property_type----------
Apartment                 26874
House                      2429
Townhouse                  1081
Loft                       1030
Condominium                 818
Serviced apartment          434
Guest suite                 158
Other                        91
Boutique hotel               68
Bed and breakfast            67
Resort                       64
Guesthouse                   35
Hostel                       32
Hotel                        29
Villa                        19
Bungalow                     19
Tiny house                    9
Aparthotel                    5
Boat                          5
Camper/RV                     3
Tent                          3
Cottage                       3
Houseboat                     1
Cabin                         1
Chalet                        1
Timeshare                     1
Train                         1
Island                        1
Casa particular (Cuba)        1
Name: property_type, dtype: int64
----------room_type----------
Entire home/apt    17443
Private room       15080
Shared room          760
Name: room_type, dtype: int64
----------bed_type----------
Real Bed         32655
Futon              249
Pull-out Sofa      193
Airbed             129
Couch               57
Name: bed_type, dtype: int64
----------amenities----------
{}                                                                                                                                                                                                                                                                                                                                                                                                                                                           112
{TV,"Cable TV",Wifi,"Air conditioning",Kitchen,Gym,Elevator,Heating,Washer,Dryer,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Private living room","Hot water","Bed linens",Microwave,"Coffee maker",Refrigerator,Dishwasher,"Dishes and silverware","Cooking basics",Oven,Stove,"BBQ grill","Long term stays allowed","Host greets you"}                        28
{TV,"Cable TV",Internet,Wifi,"Air conditioning",Kitchen,"Paid parking off premises","Pets allowed",Doorman,Gym,Elevator,Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in","Building staff","Hot water","Bed linens",Microwave,"Coffee maker",Refrigerator,Dishwasher,"Dishes and silverware",Oven,Stove}     21
{TV,Wifi,"Air conditioning",Kitchen,Heating,"Smoke detector","Carbon monoxide detector",Essentials,"Lock on bedroom door",Hangers,"Laptop friendly workspace"}                                                                                                                                                                                                                                                                                                21
{TV,Wifi,"Air conditioning",Kitchen,"Pets allowed",Gym,Elevator,Heating,Washer,Dryer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"Laptop friendly workspace"}                                                                                                                                                                                                                                                    17
                                                                                                                                                                                                                                                                                                                                                                                                                                                            ...
{TV,"Cable TV",Wifi,"Air conditioning",Kitchen,"Free street parking",Heating,"Family/kid friendly","Smoke detector","Carbon monoxide detector",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in","Smart lock","Private living room","Hot water","Bed linens","Luggage dropoff allowed"}                                                                                                                                 1
{TV,Wifi,"Air conditioning",Kitchen,Heating,"Family/kid friendly","Smoke detector",Essentials,Shampoo,Hangers,"Hair dryer",Iron}                                                                                                                                                                                                                                                                                                                               1
{TV,"Cable TV",Internet,Wifi,"Air conditioning",Kitchen,Elevator,"Buzzer/wireless intercom",Heating,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials}                                                                                                                                                                                                                                                                                1
{TV,"Cable TV",Internet,Wifi,"Air conditioning",Kitchen,"Buzzer/wireless intercom",Heating,"Family/kid friendly","Smoke detector","Carbon monoxide detector",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self check-in",Lockbox}                                                                                                                                                                                                 1
{TV,"Cable TV",Internet,Wifi,"Air conditioning",Kitchen,"Paid parking off premises","Free street parking","Buzzer/wireless intercom",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Children’s books and toys","Hot water","Luggage dropoff allowed","Long term stays allowed","Host greets you"}                        1
Name: amenities, Length: 31135, dtype: int64
----------instant_bookable----------
f    21898
t    11385
Name: instant_bookable, dtype: int64
----------cancellation_policy----------
strict_14_with_grace_period    15214
flexible                       10249
moderate                        7704
super_strict_60                   81
super_strict_30                   33
strict                             1
long_term                          1
Name: cancellation_policy, dtype: int64
----------require_guest_phone_verification----------
f    32398
t      885
Name: require_guest_phone_verification, dtype: int64

In [341]:
# airbnb["neighbourhood_cleansed"].value_counts().sort_values().tolist()

In [334]:
# 进行feature tranformation
def engineer_features(df):
    # transform host_since
    since = pd.to_datetime(df["host_since"]).dt
    df = df.drop("host_since", axis = 1)
    df["since"] = since.year
    # transform binary columns
    tfmap = {"f": 0, "t": 1}
    df["host_is_superhost"] = df["host_is_superhost"].fillna("f").map(tfmap)
    df["host_identity_verified"] = df["host_identity_verified"].fillna("f").map(tfmap)
    df["require_guest_phone_verification"] = df["require_guest_phone_verification"].map(tfmap)
    df["instant_bookable"] = df["instant_bookable"].map(tfmap)
    # transform amenities
    df["amenities"] = airbnb["amenities"].str.replace("{", "", regex = False)\
                                             .replace("}", "", regex = False)\
                                             .str.split(",").apply(len)
    # transform property types
    ptmap = {"Villa":"Other",
             "Bungalow":"Other",
             "Tiny house":"Other",
             "Aparthotel":"Other",
             "Boat":"Other",
             "Camper/RV":"Other",
             "Tent":"Other",
             "Cottage":"Other",
             "Houseboat":"Other",
             "Cabin":"Other",
             "Chalet":"Other",
             "Timeshare":"Other",
             "Train":"Other",
             "Island":"Other",
             "Casa particular (Cuba)":"Other"}
    df["property_type"].replace(ptmap, inplace = True)
    # transforom cancellation policy
    cpmap = {"super_strict_60": "strict",
             "super_strict_30": "strict",
             "strict": "strict",
             "long_term": "strict"}
    df["cancellation_policy"].replace(cpmap, inplace = True)
    # na
    return df
engineer_features(cur).iloc[:, 3:]

,neighbourhood_group_cleansed,property_type,room_type,accommodates,bathrooms,bedrooms,beds,bed_type,amenities,price,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_phone_verification,reviews_per_month,since
0,Brooklyn,Loft,Entire home/apt,2,1.0,1.0,1.0,Real Bed,24,145.0,...,10.0,10.0,10.0,10.0,10.0,1,flexible,0,0.59,2012.0
1,Manhattan,House,Entire home/apt,8,1.0,3.0,5.0,Real Bed,36,175.0,...,9.0,9.0,9.0,9.0,9.0,1,moderate,0,2.47,2013.0
2,Manhattan,Apartment,Entire home/apt,2,1.0,0.0,1.0,Real Bed,14,180.0,...,9.0,9.0,10.0,10.0,10.0,0,moderate,0,0.89,2012.0
3,Brooklyn,Apartment,Private room,1,1.0,1.0,1.0,Real Bed,19,42.0,...,NaN,NaN,NaN,NaN,NaN,0,flexible,0,NaN,2013.0
4,Brooklyn,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,19,80.0,...,10.0,10.0,10.0,10.0,10.0,0,flexible,0,3.14,2012.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33533,Manhattan,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,6,110.0,...,8.0,9.0,9.0,9.0,8.0,0,strict_14_with_grace_period,0,0.44,2012.0
33534,Manhattan,Serviced apartment,Entire home/apt,8,3.0,4.0,4.0,Real Bed,32,1195.0,...,9.0,10.0,10.0,10.0,9.0,0,strict_14_with_grace_period,0,2.28,2015.0
33535,Queens,House,Private room,1,NaN,1.0,1.0,Real Bed,1,50.0,...,NaN,NaN,NaN,NaN,NaN,0,flexible,0,NaN,2012.0
33536,Manhattan,Apartment,Private room,2,1.0,1.0,1.0,Real Bed,21,60.0,...,10.0,10.0,10.0,10.0,10.0,0,moderate,0,0.10,2014.0
33537,Manhattan,Apartment,Entire home/apt,8,2.0,3.0,4.0,Real Bed,32,325.0,...,9.0,10.0,10.0,10.0,9.0,1,strict_14_with_grace_period,0,2.76,2017.0

In [352]:
cur = engineer_features(cur)

In [353]:
cur.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33283 entries, 0 to 33537
Data columns (total 28 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   host_is_superhost                 33283 non-null  int64
 1   host_identity_verified            33283 non-null  int64
 2   neighbourhood_cleansed            33283 non-null  object
 3   neighbourhood_group_cleansed      33283 non-null  object
 4   property_type                     33283 non-null  object
 5   room_type                         33283 non-null  object
 6   accommodates                      33283 non-null  int64
 7   bathrooms                         33223 non-null  float64
 8   bedrooms                          33250 non-null  float64
 9   beds                              33252 non-null  float64
 10  bed_type                          33283 non-null  object
 11  amenities                         33283 non-null  int64
 12  price                             33283 non-null  float64
 13  guests_included                   33283 non-null  int64
 14  extra_people                      33283 non-null  float64
 15  number_of_reviews                 33283 non-null  int64
 16  review_scores_rating              25620 non-null  float64
 17  review_scores_accuracy            25591 non-null  float64
 18  review_scores_cleanliness         25605 non-null  float64
 19  review_scores_checkin             25575 non-null  float64
 20  review_scores_communication       25595 non-null  float64
 21  review_scores_location            25577 non-null  float64
 22  review_scores_value               25574 non-null  float64
 23  instant_bookable                  33283 non-null  int64
 24  cancellation_policy               33283 non-null  object
 25  require_guest_phone_verification  33283 non-null  int64
 26  reviews_per_month                 26336 non-null  float64
 27  since                             33278 non-null  float64
dtypes: float64(14), int64(8), object(6)
memory usage: 8.4+ MB

In [359]:
def fill_missing(df):
    df["bathrooms"] = df.groupby("room_type")["bathrooms"].transform(lambda x: x.fillna(x.mode()))
    df["bedrooms"] = df.groupby("accommodates")["bedrooms"].transform(lambda x: x.fillna(x.mode()))
    df["beds"] = df.groupby("accommodates")["beds"].transform(lambda x: x.fillna(x.mode()))

In [364]:
cur[cur["bedrooms"].isnull()]

,host_is_superhost,host_identity_verified,neighbourhood_cleansed,neighbourhood_group_cleansed,property_type,room_type,accommodates,bathrooms,bedrooms,beds,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,cancellation_policy,require_guest_phone_verification,reviews_per_month,since
536,0,0,Hell's Kitchen,Manhattan,Apartment,Private room,1,1.0,NaN,1.0,...,10.0,10.0,10.0,9.0,10.0,0,moderate,0,0.05,2012.0
1710,0,0,East Village,Manhattan,Apartment,Private room,1,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,0,flexible,0,NaN,2018.0
3804,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.99,2011.0
4843,0,1,Flatiron District,Manhattan,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,8.0,9.0,9.0,10.0,8.0,0,strict_14_with_grace_period,0,0.29,2009.0
5189,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,9.0,9.0,10.0,8.0,9.0,0,strict_14_with_grace_period,1,0.34,2011.0
6376,0,1,Williamsburg,Brooklyn,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,10.0,10.0,0,strict_14_with_grace_period,0,0.63,2011.0
7138,0,0,Harlem,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,0,0.44,2012.0
7462,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,9.0,7.0,9.0,0,strict_14_with_grace_period,1,0.02,2011.0
8722,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.10,2011.0
9031,1,1,Chelsea,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,10.0,9.0,0,strict_14_with_grace_period,0,4.22,2015.0
10837,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.09,2011.0
10894,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.60,2011.0
11053,1,1,SoHo,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,10.0,10.0,0,moderate,0,0.87,2011.0
11441,0,1,Upper East Side,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,9.0,10.0,10.0,10.0,9.0,1,moderate,0,0.20,2016.0
13023,0,1,Fort Greene,Brooklyn,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,10.0,10.0,0,moderate,0,0.02,2012.0
13184,0,1,Upper West Side,Manhattan,Loft,Entire home/apt,4,1.0,NaN,1.0,...,10.0,10.0,10.0,10.0,10.0,0,moderate,1,0.18,2012.0
15276,0,0,East Village,Manhattan,Apartment,Private room,1,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,0,flexible,0,NaN,2018.0
15476,0,1,West Village,Manhattan,Apartment,Entire home/apt,2,NaN,NaN,1.0,...,8.0,10.0,10.0,10.0,9.0,0,strict_14_with_grace_period,0,0.54,2009.0
16856,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,9.0,10.0,10.0,7.0,10.0,0,strict_14_with_grace_period,1,0.07,2011.0
16980,0,1,East Village,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,9.0,10.0,10.0,10.0,9.0,0,flexible,0,0.31,2012.0
17540,0,1,East Village,Manhattan,Apartment,Entire home/apt,3,1.0,NaN,2.0,...,10.0,10.0,10.0,10.0,9.0,0,strict_14_with_grace_period,0,0.25,2010.0
19327,0,0,Tompkinsville,Staten Island,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,10.0,10.0,10.0,9.0,10.0,0,strict_14_with_grace_period,1,0.11,2012.0
19437,0,1,Williamsburg,Brooklyn,Loft,Entire home/apt,4,1.0,NaN,2.0,...,9.0,10.0,9.0,10.0,10.0,0,strict_14_with_grace_period,0,0.09,2009.0
21015,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.50,2011.0
24487,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,10.0,0,strict_14_with_grace_period,1,0.49,2011.0
24524,0,0,Williamsburg,Brooklyn,Apartment,Entire home/apt,3,1.0,NaN,1.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,0,0.91,2009.0
26682,0,0,Gramercy,Manhattan,Apartment,Entire home/apt,2,1.0,NaN,1.0,...,9.0,10.0,10.0,10.0,9.0,0,moderate,1,0.08,2012.0
27368,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.54,2011.0
28580,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,10.0,0,strict_14_with_grace_period,1,0.94,2011.0
29362,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,9.0,0,strict_14_with_grace_period,1,0.04,2011.0
29596,0,0,East Village,Manhattan,Apartment,Private room,1,1.0,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,0,flexible,0,NaN,2018.0
31657,0,1,Greenpoint,Brooklyn,Apartment,Entire home/apt,4,1.0,NaN,2.0,...,10.0,10.0,10.0,9.0,10.0,0,strict_14_with_grace_period,1,0.28,2011.0
33180,0,0,Bedford-Stuyvesant,Brooklyn,Apartment,Private room,1,1.0,NaN,NaN,...,6.0,9.0,10.0,9.0,9.0,0,flexible,0,0.23,2016.0

In [367]:
cur.groupby("accommodates")["bedrooms"].transform(lambda x: x.fillna(x.median())).sum()

39184.0

In [368]:
cur.groupby("room_type")["bedrooms"].transform(lambda x: x.fillna(x.median())).sum()

39184.0

In [349]:
# Column transformer
categorical = ["neighbourhood_cleansed", "neighbourhood_group_cleansed", "property_type", "room_type", "bed_type", "cancellation_policy"]
clt = ColumnTransformer(
    transformers=[("one-hot", OneHotEncoder(handle_unknown="ignore", sparse=False), categorical)],
    remainder="passthrough"
)
clt.fit(engineer_features(cur))
clt.transform(engineer_features(cur))

array([[0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 5.900e-01,
        2.012e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 2.470e+00,
        2.013e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 8.900e-01,
        2.012e+03],
       ...,
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00,       nan,
        2.012e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 1.000e-01,
        2.014e+03],
       [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 2.760e+00,
        2.017e+03]])

In [ ]:
cheat = pd.read_csv("test.csv")
cheat.head()